version: "3.8"

services:
  ocr_api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - paddleocr_cache:/root/.paddleocr
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

volumes:
  paddleocr_cache:
